# Render deployment configuration
services:
  # Frontend service
  - type: web
    name: indivest-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://indivest-backend.onrender.com
      - key: VITE_ALPHA_VANTAGE_API_KEY
        sync: false
      - key: VITE_NEWS_API_KEY
        sync: false
      - key: VITE_FMP_API_KEY
        sync: false
      - key: VITE_TWELVE_DATA_API_KEY
        sync: false

  # Backend service
  - type: web
    name: indivest-backend
    env: python
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: ENVIRONMENT
        value: production